demo/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.conf import settings
from userprofile.views import get_profiles

admin.autodiscover()

urlpatterns = patterns('',

    # Demo FrontPage$
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html' }),

    # Profile application
    (r'^accounts/', include('userprofile.urls')),

    # Admin (not really needed)
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
)

# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.DEBUG:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

profile/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to, direct_to_template
from profile.views import *
from django.conf import settings

urlpatterns = patterns('',
    # Private profile
    (r'^$', private, {'APIKEY': settings.APIKEY, 'template': 'profile/private.html'}),
    (r'^save/$', save),
    (r'^delete/$', delete, {'template': 'profile/delete.html'}),
    (r'^delete/done/$', direct_to_template, {'template': 'profile/delete_done.html'}),
    (r'^avatar/delete/$', avatarDelete),
    (r'^avatar/delete/(?P<avatar_id>[0-9]+)/$', avatarDelete),
    (r'^avatar/choose/$', avatarChoose, {'template': 'profile/avatar_choose.html'}),
    (r'^avatar/crop/(?P<avatar_id>[0-9]+)/$', avatarCrop, {'template': 'profile/avatar_crop.html'}),
    (r'^getcountry_info/(?P<lat>[0-9\.\-]+)/(?P<lng>[0-9\.\-]+)/$', fetch_geodata),

    # Public profile
    (r'^users/(?P<user>[a-zA-Z0-9\-_]*)/$', public, {'APIKEY': settings.APIKEY, 'template': 'profile/public.html'}),

    # Vcard
    #(r'^users/(?P<user>[^/]*)/card/$', 'django.views.generic.list_detail.object_detail', dict(queryset=Foo.objects.all(), slug_field='slug', template_name="microformats/vcard.html",mimetype="text/x-vcard") ),
)

tags/0.5/demo/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf import settings
from userprofile.views import get_profiles

urlpatterns = patterns('',

    # Demo FrontPage$
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html' }),

    # Profile application
    (r'^accounts/', include('userprofile.urls')),

    # Admin (not really needed)
    (r'^admin/', include('django.contrib.admin.urls')),

)

# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.DEBUG:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

urls.py
from django.conf.urls.defaults import *
from google.appengine.api import users
from django.views.generic.simple import direct_to_template
from userprofile.views import get_profiles, get_current_user

urlpatterns = patterns('',

    # Demo FrontPage$
    (r'^$', direct_to_template, {'extra_context': { 'user': get_current_user, 'profiles': get_profiles }, 'template': 'front.html' }),

    # Profile application
    (r'^accounts/', include('userprofile.urls')),

)

tags/version-0.1/profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
import datetime
import os.path

class Continent(models.Model):
    """
    Continent class. Simple class with the information about continents.
    It can be filled up with calling the "importdata" method:

    >>> Continent().importdata()

    """
    slug = models.SlugField(prepopulate_from=('name',), unique=True)
    code = models.CharField(maxlength=2, primary_key=True)
    name = models.CharField(maxlength=255, unique=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/continent/%i/" % self.id

    def importdata(self):
        Continent.objects.all().delete()
        Continent(name="Asia", slug=slugify("Asia"), code="AS").save()
        Continent(name="Africa", slug=slugify("Africa"), code="AF").save()
        Continent(name="Europe", slug=slugify("Europe"), code="EU").save()
        Continent(name="North America", slug=slugify("North America"), code="NA").save()
        Continent(name="South America", slug=slugify("South America"), code="SA").save()
        Continent(name="Oceania", slug=slugify("Oceania"), code="OC").save()
        Continent(name="Antarctica", slug=slugify("Antarctica"), code="AN").save()

    class Admin:
        pass

    class Meta:
        verbose_name = _('Continent')
        verbose_name_plural = _('Continents')

class Country(models.Model):
    """
    Country class with the countries data needed in the Profile class. Dependent
    of the Continent class.
    To fill it with data, he needes the file "countries.txt":
    >>> Country().importdata()
    """
    name = models.CharField(maxlength=255, unique=True)
    slug = models.SlugField(prepopulate_from=('name',), unique=True)
    code = models.CharField(maxlength=2, primary_key=True)
    continent = models.ForeignKey(Continent)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/country/%i/" % self.id

    def importdata(self, file="db/countries.txt"):
        Country.objects.all().delete()
        f = open(file)
        for line in f.xreadlines():
            line = line.strip()
            d, name = line.split('"')[:-1]
            continent, code = d.split(",")[:-1]
            c = Continent.objects.filter(code=continent)[0]
            p = Country(name=name, slug=slugify(name), code=code, continent=c)
            p.save()

    class Admin:
        list_display = ('name', 'continent')
        list_filter = ['continent']

    class Meta:
        ordering = ['name']
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')


class Avatar(models.Model):
    """
    Avatar class. Every user can have one avatar associated.
    """
    photo = models.ImageField(upload_to="avatars/%Y/%b/%d")
    date = models.DateTimeField(default=datetime.datetime.now)
    user = models.OneToOneField(User, blank=True, null=True)
    valid = models.BooleanField(default=False)

    def get_absolute_url(self):
        return "/site_media/%s" % self.photo

    def __unicode__(self):
        return "%s-%s" % (self.user, self.photo)

    class Admin:
        pass

class Profile(models.Model):
    """
    User profile model
    """

    GENDER_CHOICES = ( ('F', _('Female')), ('M', _('Male')),)

    firstname = models.CharField(maxlength=255, blank=True)
    surname = models.CharField(maxlength=255, blank=True)
    user = models.ForeignKey(User, unique=True, edit_inline=models.TABULAR,
                             num_in_admin=1,min_num_in_admin=1, max_num_in_admin=1,
                             num_extra_on_change=0)
    birthdate = models.DateTimeField(default=datetime.datetime.now(), blank=True)
    url = models.URLField(blank=True, core=True)
    about = models.TextField(blank=True)
    latitude = models.DecimalField(max_digits=8, decimal_places=6, default=-100)
    longitude = models.DecimalField(max_digits=8, decimal_places=6, default=-100)
    gender = models.CharField(maxlength=1, choices=GENDER_CHOICES, blank=True)
    country = models.ForeignKey(Country, blank=True, null=True)
    location = models.CharField(maxlength=255, blank=True)

    class Admin:
        pass

    def __unicode__(self):
        return "%s" % self.user

    def yearsold(self):
        return (datetime.datetime.now().toordinal() - self.birthdate.toordinal()) / 365

tags/version-0.1/profile/forms.py
from django import newforms as forms
from django.core.exceptions import ObjectDoesNotExist
from profile.models import Profile, Avatar

def ProfileForm(request):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    user = request.user
    profile,created = Profile.objects.get_or_create(user=user)

    ProfileEdit = forms.form_for_instance(profile)
    del ProfileEdit.base_fields['user']
    ProfileEdit.base_fields['birthdate'].initial = profile.birthdate.strftime("%Y-%m-%d")
    if request.method == "POST":
        form = ProfileEdit(request.POST, request.FILES)
    else:
        form = ProfileEdit()

    return form

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField()

userprofile/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.models import User, SiteProfileNotAvailable
from userprofile.models import EmailValidation, AVATAR_SIZES, DEFAULT_AVATAR_SIZE, MIN_AVATAR_SIZE
from django.core.files.uploadedfile import SimpleUploadedFile
import mimetypes, urllib
from django.contrib.auth.forms import UserCreationForm

if not settings.AUTH_PROFILE_MODULE:
    raise SiteProfileNotAvailable
try:
    app_label, model_name = settings.AUTH_PROFILE_MODULE.split('.')
    Profile = models.get_model(app_label, model_name)
except (ImportError, ImproperlyConfigured):
    raise SiteProfileNotAvailable

class LocationForm(forms.ModelForm):
    """
    Profile location form
    """

    class Meta:
        model = Profile
        fields = ('location', 'latitude', 'longitude', 'country')

class ProfileForm(forms.ModelForm):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'location', 'latitude', 'longitude', 'country',
                   'user', 'public', 'site')

class PublicFieldsForm(forms.ModelForm):
    """
    Public Fields of the Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'user', 'public')

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField(required=False, help_text=_("Select an image from disk"))
    url = forms.URLField(required=False, help_text=_("Select an image from a remote URL. Put the URL on the input below and we'll retrieve the image for you"))

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if not url: return ''
        try:
            filename, headers = urllib.urlretrieve(url)
        except:
            raise forms.ValidationError(forms.fields.URLField.default_error_messages['invalid_link'])
        if not mimetypes.guess_all_extensions(headers.get('Content-Type')):
            raise forms.ValidationError(_('The file type is invalid: %s' % type))
        return SimpleUploadedFile(filename, open(filename).read(), content_type=headers.get('Content-Type'))

    def clean(self):
        if not (self.cleaned_data.get('photo') or self.cleaned_data.get('url')):
            raise forms.ValidationError(_('You must enter one of the options'))
        return self.cleaned_data

class AvatarCoordinateField(forms.IntegerField):
    def clean(self, value):
        try:
            value = int(float(value))
        except:
            pass
        return super(AvatarCoordinateField, self).clean(value)

class AvatarCropForm(forms.Form):
    """
    Crop dimensions form
    """
    top = AvatarCoordinateField()
    bottom = AvatarCoordinateField()
    left = AvatarCoordinateField()
    right = AvatarCoordinateField()

    def __init__(self, image=None, *args, **kwargs):
        self.image = image
        super(AvatarCropForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.cleaned_data.get('right') and self.cleaned_data.get('left') and \
           int(self.cleaned_data.get('right')) - int(self.cleaned_data.get('left')) < MIN_AVATAR_SIZE:
            raise forms.ValidationError(_("You must select a portion of the image with a minimum of %(min_avatar_size)dx%(min_avatar_size)d pixels.") % { 'min_avatar_size': MIN_AVATAR_SIZE })

        return self.cleaned_data



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=getattr(settings, "REQUIRE_EMAIL_CONFIRMATION", False), label=_("E-mail address"))

    class Meta:
        model = User
        fields = ("username","email",)

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")

        if not email: return  email

        try:
            User.objects.get(email__iexact=email)
            raise forms.ValidationError(_("That e-mail is already used."))
        except User.DoesNotExist:
            try:
                EmailValidation.objects.get(email=email)
                raise forms.ValidationError(_("That e-mail is already being confirmed."))
            except EmailValidation.DoesNotExist:
                return email

    def save(self, *args, **kwargs):
        user = super(RegistrationForm, self).save(commit=False)
        user.is_active = not getattr(settings, "REQUIRE_EMAIL_CONFIRMATION", False)
        user.save()
        if self.cleaned_data.get('email'):
            EmailValidation.objects.add(user=user, email=user.email)
        return user

try:
    _temp = settings.REGISTRATION_FORM.split('.')
    _form_class = _temp.pop()
    _module = __import__('.'.join(_temp), globals(), locals(), [_form_class])
    _RegistrationForm = getattr(_module, _form_class)
except:
    _RegistrationForm = RegistrationForm

class EmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if not (User.objects.filter(email=email) or EmailValidation.objects.filter(email=email)):
            return email

        raise forms.ValidationError(_("That e-mail is already used."))

class ResendEmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email) or EmailValidation.objects.filter(email=email):
            return email

        raise forms.ValidationError(_("That e-mail isn't registered."))

tags/version-0.1/profile/templates/profile/avatar.html
<html>
<head>
{% load i18n %}
    <title>{% trans "Change avatar" %}</title>
    <link rel="stylesheet" href="/site_media/css/common.css" type="text/css" />
    <script type="text/javascript" src="/site_media/js/jquery-1.2.1.js"></script>
    <script type="text/javascript" src="/site_media/js/jquery.dimensions.js"></script>
    <script type="text/javascript" src="/site_media/js/ui/ui.mouse.js"></script>
    <script type="text/javascript" src="/site_media/js/ui/ui.draggable.js"></script>
    <script type="text/javascript" src="/site_media/js/ui/ui.draggable.ext.js"></script>
    <script type="text/javascript" src="/site_media/js/ui/ui.resizable.js"></script>
    <script type="text/javascript" src="/site_media/js/jquery.avatar.js"></script>
    <style tyle="text/css">
			body {min-width: 500px; min-height: 240px;}
		</style>
{%if done %}
    <script type="text/javascript">
     	window.close();
			window.opener.document.images.avatar.src = "{{ avatar.get_absolute_url }}";
    </script>
{% else %}
{% if avatar %}
<script type="text/javascript">

	var width = {{ width }};
	var height = {{ height }};
  if (width < 500 ) { width = 500; }
  window.resizeTo(width + 30, height + 120);

</script>
{% endif %}
{% endif %}
</head>
<body style="background: #b2e6ad;">
  {% if avatar.photo %}
  <form class="avatarform" action="/profile/avatar/two/" method="post" enctype="multipart/form-data">
		<p class="green">
    	<input type="submit" class="buttoncancel" value="{% trans 'Cancel' %}" />
    	<input type="submit" class="buttondone" value="{% trans 'Select portion' %}" />
    	<input type="submit" class="buttonanother" value="{% trans 'Select anoter image' %}" />
    	<input type="hidden" name="avatar_id" id="avatar_id" value="{{ avatar.pk }}" />
    	<input type="hidden" name="top" id="id_top" value="" />
    	<input type="hidden" name="left" id="id_left" value="" />
    	<input type="hidden" name="size" id="id_size" value="" />
		</p>
  </form>
  <center style="padding-top: 20px;">
    <div style="position: relative; background: url({{ blur_url }}) no-repeat; margin: 0px; width: {{width}}px; height: {{height}}px;" class="parent" id="avatarzone">
      <div id="child" class="child ui-wrapper" style="position: absolute; width: {{cropsize}}px; height: {{cropsize}}px; left: {{cx}}px; top: {{cy}}px; border: 0px; background: url({{ avatar.get_absolute_url }}) no-repeat; background-position: -{{ cx }}px -{{ cy }}px;">
        <div style="position: absolute; top: 0px; left: 0px; width: 4px; height: 100%; background: red;"></div>
        <div style="position: absolute; top: 0px; right: 0px; width: 4px; height: 100%; background: red;"></div>
        <div style="position: absolute; bottom: 0px; left: 0px; width: 100%; height: 4px; font-size: 1px; background: red;"></div>
        <div style="position: absolute; top: 0px; left: 0px; width: 100%; height: 4px; font-size: 1px; background: red;"></div>
				<div class='ui-resizable-nw ui-resizable-handle'></div>
				<div class='ui-resizable-sw ui-resizable-handle'></div>
				<div class='ui-resizable-ne ui-resizable-handle'></div>
        <div class="ui-resizable-se ui-resizable-handle"></div>
      </div>
    </div>
  </center>
	{% else %}
	<p class="green">{% trans "Select the image file from your computer you want to assign as your avatar in your profile:" %}</p>
  <form style="padding: 10px;" class="userdata" action="" method="post" enctype="multipart/form-data">
    <label style="line-height: 16px;" for="id_avatar">{% trans "Avatar:" %}</label>
    {{ form.photo }}
    <input type="submit" class="buttoncancel" value="{% trans 'Cancel' %}" />
  </form>
	<div id="loading" style="margin: auto; width: 180px; font-weight: bold; overflow: hidden; display: none;"><img style="float: left;" src="/site_media/images/loading2.gif" /><p style="margin-left: 10px; float: left; line-height: 34px;">{% trans "Please wait..." %}</p></div>
	{% endif %}
</body>
</html>

tags/version-0.1/profile/templates/profile/delete_confirm.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "Delete all your personal information" %}{% endblock %}
{% block content %}
  <h2>{% trans "Delete all your personal information" %}</h2>
  <form class="userdata" action="" method="POST">
		<fieldset>
			<p>Are you sure?</p>
    	<input type="submit" value="Yes" />
		</fieldset>
  </form>
	<br />
  <p><a href="/profile">No, return to my profile</a></p>
{% endblock %}

tags/version-0.1/profile/templates/profile/delete_success.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans 'Delete all my personal information' %}{% endblock %}

{% block content %}

<h2>{% trans 'Delete all my personal information' %}</h2>
<p>{% trans 'Profile information deleted successfully' %}</p>
<p><a href="/profile">Return to my profile</a></p>
{% endblock %}

tags/version-0.1/profile/templates/profile/private.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}{{ user }}'s Dashboard{% endblocktrans %}{% endblock %}
{% block customjs %}
<script type="text/javascript" src="http://www.google.com/jsapi?key={{ apikey }}"></script>
<script type="text/javascript" src="/site_media/js/jquery.jmaps.1.4.js"></script>
<script type="text/javascript" src="/site_media/js/ui.datepicker.js"></script>
{% ifequal request.LANGUAGE_CODE 'es' %}
<script type="text/javascript" src="/site_media/js/ui.datepicker-es.js"></script>
{% endifequal %}
<script type="text/javascript" src="/site_media/js/jquery.profile.js"></script>
<link rel="stylesheet" href="/site_media/css/ui.datepicker.css" type="text/css" />
{% endblock %}

{% block content %}
<h1>{% trans "Tell others something about you" %}</h1>
<form class="userdata biglabel" action="" method="post" enctype="multipart/form-data">
  <fieldset>
    {{ form.errors }}
		<div class="right">
			<div class="box">
    		<p class="title">{% trans "Avatar:" %}</p>
    		<p class="title"><a class="avatar" href="/profile/avatar/one/">{% trans "Change" %}</a> <a class="delavatar" href="/profile/avatar/delete">{% trans "Delete" %}</a></p>
      	{% if avatar %}
      		<a class="avatar" href="/profile/avatar/one/"><img id="avatar" src="{{ avatar.get_absolute_url }}" /></a>
      	{% else %}
      		<a class="avatar" href="/profile/avatar/one/"><img id="avatar" src="/site_media/images/default.gif" /></a>
      	{% endif %}
			</div>
			<br />
			<div class="box">
    		<p class="title">{% trans "Birth date:" %}</p>
    		<p style="text-align: center"><span class="calendarInline"></span></p>
			</div>
		</div>
		<div>
			<p class="savedmsg"><img src="/site_media/images/loading2.gif">{% trans "Saving profile..." %}</p>
    	<input style="margin-bottom: 10px;" type="button" class="save" value="{% trans 'Save' %}" />
		</div>
		<br />
    <label for="id_username">{% trans "Username:" %}</label>
    <p style="line-height: 29px;"><span style="font-size: 16px; font-weight: bold;">{{ user }}</span> <a href="/accounts/password/change">{% trans "(Change password)" %}</a></p>
    <label for="id_email">{% trans "E-mail:" %}</label>
    <p style="line-height: 29px;"><span style="font-size: 16px; font-weight: bold;">{%if not email %}{% trans "Not set yet" %}{% else %}{{ email }}{% endif %}</span> (<a href="/accounts/email/change">{% trans "Add your e-mail address" %}</a>)</p>
    <label for="id_firstname">{% trans "First Name:" %}</label>
    {{ form.firstname }}
    <label for="id_surname">{% trans "Surname:" %}</label>
    {{ form.surname }}
	<div>
    <label for="id_gender">{% trans "Gender:" %}</label>
		<div id="gender"><a class="male" href="">{% trans "Male" %}</a><a class="female" href="">{% trans "Female" %}</a></div>
	</div>
    <br />
		<div class="newselect">
    	<label for="id_country">{% trans "Country:" %}</label>
    	{{ form.country }}
			<img id="country_loading" style="display: none;" src="/site_media/images/loading.gif" />
		</div>
		<div id="countrydetail" style="margin-bottom: 5px;">
    	<label for="id_location">{% trans "Location:" %}</label>
			{{ form.location }} <input style="float: left;" id="clearLocation" type="button" value="Clear" /> <input style="float: left;" id="searchAddress" type="button" value="Lookup" />
    	<br />
    	<label for="id_position">{% trans "Position:" %}</label>
			<div id="jmap"></div>
    	<br />
		</div>
    <label for="id_url">{% trans "Url:" %}</label>
    {{ form.url }}
    <div id="urlmsg" class="message">
    {% if form.url.errors %}{{ form.url.errors|join:", " }}{% endif %}
    </div>
    <br />
    <label for="id_about">{% trans "About:" %}</label>
    {{ form.about }}
    <div id="aboutmsg" class="message">
    {% if form.about.errors %}{{ form.about.errors|join:", " }}{% endif %}
    </div>
    <br />
		<div style="margin-top: 5px;">
    <label for="id_passwd">{% trans "Other actions:" %}</label>
    <p style="line-height: 29px;"><a style="font-size: 16px; font-weight: bold;" href="/profile/delete">{% trans "Delete all my personal information" %}</a></p>
		</div>
    <br />
    <div style="display:none;">{{ form.birthdate }}{{ form.latitude }}{{ form.longitude }}{{ form.gender }}</div>
		<div>
      <p class="savedmsg"><img src="/site_media/images/loading2.gif">{% trans 'Saving profile...' %}</p>
    	<input type="button" class="save" value="{% trans 'Save' %}" />
		</div>
  </fieldset>
</form>
<br />
{% endblock %}

tags/version-0.1/profile/templates/profile/usercard.html
{% load i18n %}
<div class="vcard">
<img class="photo" src="{{ avatar_url }}" alt="{{ user }}"/>
<ul style="float: left;">
  <li class="fn nickname">{{ user }}</li>
	{% if profile.country %}
	<li>{{ profile.country }}</li>
	{% else %}
	<li>{% trans "No country" %}</li>
	{% endif %}
	{% if yearsold %}
	<li>{% blocktrans %}{{ yearsold }} years old{% endblocktrans %}</li>
	{% endif %}
	{% if profile.url %}
	<li><a class="url" href="{{ profile.url }}">{% trans "My Website" %}</a></li>
	{% endif %}
	{% if gender_img %}
	<li style="margin: 10px 0px 0px 110px;"><img src="{{ gender_img }}" /></li>
	{% endif %}
</ul>
</div>