demo/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.views.generic.simple import direct_to_template
from django.conf import settings
from userprofile.views import get_profiles

admin.autodiscover()

urlpatterns = patterns('',

    # Demo FrontPage$
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html' }),

    # Profile application
    (r'^accounts/', include('userprofile.urls')),

    # Admin (not really needed)
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    (r'^admin/(.*)', admin.site.root),
)

# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.DEBUG:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

profile/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import redirect_to, direct_to_template
from profile.views import *
from django.conf import settings

urlpatterns = patterns('',
    # Private profile
    (r'^$', private, {'APIKEY': settings.APIKEY, 'template': 'profile/private.html'}),
    (r'^save/$', save),
    (r'^delete/$', delete, {'template': 'profile/delete.html'}),
    (r'^delete/done/$', direct_to_template, {'template': 'profile/delete_done.html'}),
    (r'^avatar/delete/$', avatarDelete),
    (r'^avatar/delete/(?P<avatar_id>[0-9]+)/$', avatarDelete),
    (r'^avatar/choose/$', avatarChoose, {'template': 'profile/avatar_choose.html'}),
    (r'^avatar/crop/(?P<avatar_id>[0-9]+)/$', avatarCrop, {'template': 'profile/avatar_crop.html'}),
    (r'^getcountry_info/(?P<lat>[0-9\.\-]+)/(?P<lng>[0-9\.\-]+)/$', fetch_geodata),

    # Public profile
    (r'^users/(?P<user>[a-zA-Z0-9\-_]*)/$', public, {'APIKEY': settings.APIKEY, 'template': 'profile/public.html'}),

    # Vcard
    #(r'^users/(?P<user>[^/]*)/card/$', 'django.views.generic.list_detail.object_detail', dict(queryset=Foo.objects.all(), slug_field='slug', template_name="microformats/vcard.html",mimetype="text/x-vcard") ),
)

tags/0.5/demo/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.conf import settings
from userprofile.views import get_profiles

urlpatterns = patterns('',

    # Demo FrontPage$
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html' }),

    # Profile application
    (r'^accounts/', include('userprofile.urls')),

    # Admin (not really needed)
    (r'^admin/', include('django.contrib.admin.urls')),

)

# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.DEBUG:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

urls.py
from django.conf.urls.defaults import *
from google.appengine.api import users
from django.views.generic.simple import direct_to_template
from userprofile.views import get_profiles, get_current_user

urlpatterns = patterns('',

    # Demo FrontPage$
    (r'^$', direct_to_template, {'extra_context': { 'user': get_current_user, 'profiles': get_profiles }, 'template': 'front.html' }),

    # Profile application
    (r'^accounts/', include('userprofile.urls')),

)

tags/0.3/userprofile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from django.conf import settings
import datetime
import Image, ImageFilter
import os.path

AVATARSIZES = ( 128, 96, 64, 32, 16 )
GENDER_CHOICES = ( ('F', _('Female')), ('M', _('Male')),)
GENDER_IMAGES = { "M": "%simages/male.png" % settings.MEDIA_URL, "F": "%simages/female.png" % settings.MEDIA_URL }

class Continent(models.Model):
    """
    Continent class. Simple class with the information about continents.
    It can be filled up with calling the "importdata" method:

    >>> Continent().importdata()

    """
    slug = models.SlugField(prepopulate_from=('name',), unique=True)
    code = models.CharField(max_length=2, primary_key=True)
    name = models.CharField(max_length=255, unique=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/continent/%s/" % self.slug

    def importdata(self):
        Continent.objects.all().delete()
        Continent(name="Asia", slug=slugify("Asia"), code="AS").save()
        Continent(name="Africa", slug=slugify("Africa"), code="AF").save()
        Continent(name="Europe", slug=slugify("Europe"), code="EU").save()
        Continent(name="North America", slug=slugify("North America"), code="NA").save()
        Continent(name="South America", slug=slugify("South America"), code="SA").save()
        Continent(name="Oceania", slug=slugify("Oceania"), code="OC").save()
        Continent(name="Antarctica", slug=slugify("Antarctica"), code="AN").save()

    class Admin:
        pass

    class Meta:
        verbose_name = _('Continent')
        verbose_name_plural = _('Continents')

class Country(models.Model):
    """
    Country class with the countries data needed in the Profile class. Dependent
    of the Continent class.
    To fill it with data, the file "countries.txt" is needed:
    >>> Country().importdata()
    """
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(prepopulate_from=('name',), unique=True)
    code = models.CharField(max_length=2, primary_key=True)
    continent = models.ForeignKey(Continent)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/country/%s/" % self.slug

    def importdata(self, file="db/countries.txt"):
        Country.objects.all().delete()
        f = open(file)
        for line in f.xreadlines():
            line = line.strip()
            d, name = line.split('"')[:-1]
            continent, code = d.split(",")[:-1]
            c = Continent.objects.filter(code=continent)[0]
            p = Country(name=name, slug=slugify(name), code=code, continent=c)
            p.save()

    class Admin:
        list_display = ('name', 'continent')
        list_filter = ['continent']

    class Meta:
        ordering = ['name']
        verbose_name = _('Country')
        verbose_name_plural = _('Countries')


class Avatar(models.Model):
    """
    Avatar class. Every user can have one avatar associated.
    """
    photo = models.ImageField(upload_to="avatars/%Y/%b/%d")
    date = models.DateTimeField(default=datetime.datetime.now)
    user = models.OneToOneField(User, blank=True)
    box = models.CharField(max_length=255, blank=True)
    valid = models.BooleanField(default=False)

    def get_absolute_url(self):
        return self.get_photo_url()

    def __unicode__(self):
        return "%s-%s" % (self.user, self.photo)

    class Admin:
        pass

    def save(self):

        super(Avatar, self).save()

        if self.valid:
            Avatar.objects.filter(user=self.user).exclude(pk=self.pk).delete()
            base, ext = os.path.splitext(self.get_photo_filename())

            image = Image.open(self.get_photo_filename())
            box = self.box.split("-")
            box = [ int(num) for num in box ]
            image = image.crop(box)
            if image.mode not in ('L', 'RGB'):
                image = image.convert('RGB')

            for size in AVATARSIZES:
                image.thumbnail((size, size), Image.ANTIALIAS)
                image.save("%s.%s%s" % ( base, size, ext))

            del image

    def delete(self):
        filename = self.get_photo_filename()
        base, ext = os.path.splitext(filename)
        for size in AVATARSIZES:
            try:
                os.remove("%s.%s%s" % ( base, size, ext))
            except:
                pass

        try:
            os.remove(self.get_photo_filename())
        except:
            pass

        super(Avatar, self).delete()


class Profile(models.Model):
    """
    User profile model
    """

    firstname = models.CharField(max_length=255, blank=True)
    surname = models.CharField(max_length=255, blank=True)
    user = models.OneToOneField(User)
    birthdate = models.DateField(default=datetime.date.today(), blank=True)
    date = models.DateTimeField(default=datetime.datetime.now)
    url = models.URLField(blank=True, core=True)
    about = models.TextField(blank=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=6, default=0)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, default=0)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True)
    location = models.CharField(max_length=255, blank=True)

    class Admin:
        pass

    def __unicode__(self):
        return _("%s's profile") % self.user

    def get_genderimage_url(self):
        return GENDER_IMAGES[self.gender]

    def get_absolute_url(self):
        return "/profile/users/%s/" % self.user

    def yearsold(self):
        return (datetime.date.today().toordinal() - self.birthdate.toordinal()) / 365

tags/version-0.1/profile/forms.py
from django import newforms as forms
from django.core.exceptions import ObjectDoesNotExist
from profile.models import Profile, Avatar

def ProfileForm(request):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    user = request.user
    profile,created = Profile.objects.get_or_create(user=user)

    ProfileEdit = forms.form_for_instance(profile)
    del ProfileEdit.base_fields['user']
    ProfileEdit.base_fields['birthdate'].initial = profile.birthdate.strftime("%Y-%m-%d")
    if request.method == "POST":
        form = ProfileEdit(request.POST, request.FILES)
    else:
        form = ProfileEdit()

    return form

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField()

tags/version-0.1/profile/views.py
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from forms import ProfileForm, AvatarForm
from models import Profile
from django.core.exceptions import ObjectDoesNotExist
from django.utils import simplejson
from django.contrib.auth.models import User
from profile.models import Avatar, Profile
from account.models import EmailValidate
import random
import Image, ImageFilter
import urllib
from xml.dom import minidom

def fetch_geodata(request, lat, lng):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        url = "http://ws.geonames.org/countrySubdivision?lat=%s&lng=%s" % (lat, lng)
        dom = minidom.parse(urllib.urlopen(url))
        country = dom.getElementsByTagName('countryCode')
        if len(country) >=1:
            country = country[0].childNodes[0].data
        region = dom.getElementsByTagName('adminName1')
        if len(region) >=1:
            region = region[0].childNodes[0].data

        return HttpResponse(simplejson.dumps({'success': True, 'country': country, 'region': region}))
    else:
        return HttpResponseRedirect("/")

def public(request, user, template):
    cuser = User.objects.get(username=user)
    try:
        profile = Profile.objects.get(user=cuser)
        avatar = Avatar.objects.get(user=cuser, valid=True)
    except:
        pass
    user = request.user

    return render_to_response(template, locals())

@login_required
def private(request, APIKEY, template):
    """
    Private part of the user profile
    """
    apikey = APIKEY
    user = request.user

    try:
        email = EmailValidate.objects.get(user=str(user)).email
        validated = False
    except:
        email = User.objects.get(username=str(user)).email
        validated = True

    form = ProfileForm(request)

    try:
        avatar = Avatar.objects.filter(user=user, valid=True)[0]
    except:
        pass

    if request.method == "POST" and form.is_valid():
        form.save()

    profile = Profile.objects.get(user=user)
    lat = profile.latitude
    lng = profile.longitude

    return render_to_response(template, locals())

@login_required
def save(request):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        form = ProfileForm(request)
        if request.method == "POST" and form.is_valid():
            form.save()
            return HttpResponse(simplejson.dumps({'success': True}))
        else:
            return HttpResponse(simplejson.dumps({'success': False, 'error': form.errors}))
    else:
        return HttpResponseRedirect("/")

@login_required
def delete(request, template):
    user = str(request.user)
    userobj = User.objects.get(username=user)
    if request.method == "POST":
        # Remove the profile
        try:
            Profile.objects.get(user=userobj).delete()
        except:
            pass
        # Remove the avatar if exists
        try:
            Avatar.objects.get(user=userobj).delete()
        except:
            pass
        # Remove the e-mail of the account too
        acct = User.objects.get(username=user)
        acct.email = ''
        acct.save()

        return HttpResponseRedirect('%sdone/' % request.path)

    return render_to_response(template, locals())

@login_required
def avatar(request, template, step="one"):
    """
    Avatar management
    """
    if not request.method == "POST":
        form = AvatarForm()
    else:
        if step=="one":
            form = AvatarForm(request.POST, request.FILES)
            if form.is_valid():
                data = form.cleaned_data
                Avatar.objects.filter(user=request.user, valid=False).delete()
                avatar = Avatar(user=request.user)
                avatar.save_photo_file(data['photo'].filename, data['photo'].content)
                avatar.save()
                im = Image.open(avatar.get_photo_filename())

                # Resize if needed
                width = avatar.get_photo_width()
                height= avatar.get_photo_height()
                if width > height and width > 640:
                    im = im.resize((640, 640*height/width), Image.ANTIALIAS)
                    im.save(avatar.get_photo_filename())
                    width, height = im.size
                elif height > 480:
                    im = im.resize((480*width/height, 480), Image.ANTIALIAS)
                    im.save(avatar.get_photo_filename())
                    width, height = im.size

                if width < 96 or height < 96:
                    cropsize = 32
                else:
                    cropsize = 96

                cx = width/2 - 48
                if cx < 0: cx=0
                cy = height/2 - 48
                if cy < 0: cy=0

                # Generate blur and scale image
                blur = im.filter(ImageFilter.BLUR)
                blur = blur.convert("L")
                blur.save("%s_blur.jpg" % avatar.get_photo_filename())
                blur_url = "%s_blur.jpg" % avatar.get_absolute_url()


        elif step=="two":
                avatar = Avatar.objects.get(user = request.user, pk = request.POST.get('avatar_id'))
                avatar.valid = True
                avatar.save()
                im = Image.open(avatar.get_photo_filename())
                if request.POST.get('top') and request.POST.get('left') and request.POST.get('size'):
                    top = request.POST.get('top')
                    left = request.POST.get('left')
                    size = request.POST.get('size')
                    box = ( int(left), int(top), int(left) + int(size), int(top) + int(size))
                    im = im.crop(box)
                resized = im.resize((96, 96), Image.ANTIALIAS)
                resized.save(avatar.get_photo_filename())
                done = True

    return render_to_response(template, locals())

@login_required
def avatarDelete(request, avatar_id=False):
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest' and not avatar_id:
        Avatar.objects.filter(user=request.user).delete()
        return HttpResponse(simplejson.dumps({'success': True}))
    elif avatar_id:
        Avatar.objects.filter(user=request.user, pk=avatar_id).delete()
        return HttpResponse(simplejson.dumps({'success': True}))
    else:
        return HttpResponseRedirect("/")

tags/0.5/userprofile/templates/userprofile/profile/delete.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Delete personal information" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<form action="" method="post" enctype="multipart/form-data">
		<h3>{% trans "Delete your personal information" %}</h3>
		<p><label for="remove">{% trans "Are you sure?" %}</label> <input id="remove" type="submit" value="{% trans "Yes" %}" /></p>
	</form>
{% endblock %}

{% block content-related %}
	<div class="box">
		<p>{% trans "It erases all your private data except your username. You can refill the information later if you want to" %}.</p>
	</div>
{% endblock %}

tags/0.5/userprofile/templates/userprofile/profile/delete_done.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Profile removed" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<p class="success">
		{% trans "Your profile information has been removed successfully" %}.
	</p>
{% endblock %}
{% block content-related %}
  <div class="box">
    <h3>{% trans "Delete your personal information" %}</h3>
    <p>{% trans "Deleting all your personal information will erase all your private data, except your username. You can refill the information later if you want to" %}.</p>
  </div>
{% endblock %}

tags/0.5/userprofile/templates/userprofile/profile/location.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}{{ user }}'s Dashboard{% endblocktrans %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
	{% if APIKEY %}
	<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.location.js"></script>
	{% endif %}
{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<form action="{{ request.path }}" method="post" enctype="multipart/form-data">
	<fieldset>
		<legend>{% trans "Define your location" %}</legend>
		<label for="id_country">{% trans "Country" %}<img class="hide" src="{{ MEDIA_URL }}images/loading.gif" /></label>
		<p>
			<select name="country" id="id_country">
				<option value="">{% trans "Not set" %}</option>
				<option value="" disabled="disabled">{% trans "More common..." %}</option>
				<option value="ES">{% trans "Spain" %}</option>
				{% for continent,countries in country_data.items %}
					<option value="" disabled="disabled">{{ continent }}</option>
					{% for country in countries %}
					<option value="{{ country.code }}" {% ifequal profile.country.name country.name %}selected="selected"{% endifequal %}>{{ country }}</option>
					{% endfor %}
				{% endfor %}
			</select>
		</p>

		{% if APIKEY %}
			<div class="mapinfo">
				<label>{% trans "Location" %}</label>
				<p id="location_info">{{ profile.location }}</p>
				<label for="map">{% trans "Position" %}</label>
				<div id="map"></div>
			</div>
			<div class="hide">{{ form.location }}{{ form.latitude }}{{ form.longitude }}</div>
			<div style="display: none;" id="apikey">{{ APIKEY }}</div>
		{% endif %}
	</fieldset>
	<input type="submit" value="{% trans 'Save' %}" />
	</form>
{% endblock %}
{% block content-related %}
<div class="box">
  <h3>{% trans "Location information" %}</h3>
    <p>{% trans "Define your location information. Once inserted, you can make it public going to the" %} <a href="/accounts/profile/edit/public/">{% trans "public information page" %}</a>.</p>
</div>
{% endblock %}

tags/0.5/userprofile/templates/userprofile/profile/location_done.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}{{ user }}'s Dashboard{% endblocktrans %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<p class="success large">
		{% trans "Your profile information has been updated successfully" %}.
	</p>
{% endblock %}

{% block content-related %}
<div class="box">
  <h3>{% trans "Location information" %}</h3>
    <p>{% trans "Define your location information. Once inserted, you can make it public going to the" %} <a href="/accounts/profile/edit/public/">{% trans "public information page" %}</a>.</p>
</div>
{% endblock %}

tags/0.5/userprofile/templates/userprofile/profile/makepublic.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}{{ user }}'s Dashboard{% endblocktrans %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
	{% if profile.latitude and profile.longitude %}
	<script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key={{ APIKEY }}" type="text/javascript"></script>
	<script type="text/javascript">
		$(function() {
			if (GBrowserIsCompatible()) {
				this.map = new GMap2(document.getElementById("map"));
				this.map.disableDragging();
				this.map.setCenter(new GLatLng({{ profile.latitude }}, {{ profile.longitude }}), 2);
				this.marker = new GMarker(new GLatLng({{ profile.latitude }}, {{ profile.longitude }}), {clickable: false, draggable: false});
				this.map.addOverlay(this.marker);
			}
		});
	</script>
	{% endif %}
{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<form action="" method="post">
		<fieldset>
			<legend>{% trans "Name" %}</legend>
		{% if profile.firstname %}
			<input type="checkbox" name="firstname_public" {% if profile.visible.firstname %}checked="on"{% endif %}/>
			{{ profile.firstname }} {{ profile.surname }}
		{% else %}
			{% trans "Not set" %}
		{% endif %}
		</fieldset>

		<fieldset>
			<legend>{% trans "Gender" %}</legend>
		{% if profile.gender %}
			<input type="checkbox" name="gender_public" {% if profile.visible.gender %}checked="on"{% endif %} />
			{{ profile.get_gender_display }}
		{% else %}
			{% trans "Not set" %}
		{% endif %}
		</fieldset>

		<fieldset>
			<legend>{% trans "Url" %}</legend>
		{% if profile.url %}
			<input type="checkbox" name="url_public" {% if profile.visible.url %}checked="on"{% endif %} />
			<a href="{{ profile.url }}">{{ profile.url }}</a>
		{% else %}
			{% trans "Not set" %}
		{% endif %}
		</fieldset>

		<fieldset>
			<legend>{% trans "Years old" %}</legend>
		{% if profile.yearsold %}
			<input type="checkbox" name="birthdate_public" {% if profile.visible.birthdate %}checked="on"{% endif %}/>
			{{ profile.yearsold }} {% trans "years old." %}
		{% else %}
			{% trans "Not set" %}
		{% endif %}
		</fieldset>

		<fieldset>
			<legend>{% trans "About" %}</legend>
		{% if profile.about %}
			<input type="checkbox" name="about_public" {% if profile.visible.about %}checked="on"{% endif %}/>
			{{ profile.about|linebreaksbr }}
		{% else %}
			{% trans "Not set" %}
		{% endif %}
		</fieldset>

	{% if APIKEY %}
		<fieldset>
			<legend>{% trans "Country" %}</legend>
		{% if profile.country %}
			<input type="checkbox" name="country_id_public" {% if profile.visible.country_id %}checked="on"{% endif %}/>
			{{ profile.country }}
		{% else %}
			{% trans "Not set" %}
		{% endif %}
		</fieldset>

		<fieldset>
			<legend>{% trans "Location" %}</legend>
			{% if profile.location %}
			<input type="checkbox" name="location_public" {% if profile.visible.location %}checked="on"{% endif %}/>
			{{ profile.location }}
			<div id="map" style="width: 440px; height: 240px;"></div>
			{% else %}
			{% trans "Not set" %}
			{% endif %}
		</fieldset>
	{% endif %}

		<input type="submit" value="{% trans 'Save' %}" />
	</form>
{% endblock %}

{% block content-related %}
	<div class="box">
		<h3>{% trans "Public information" %}</h3>
		<p>{% trans "Select the information you have inserted on your profile that you want to make public" %}.</p>
	</div>
{% endblock %}

tags/0.5/userprofile/templates/userprofile/profile/makepublic_done.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% blocktrans %}{{ user }}'s Dashboard{% endblocktrans %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<p class="success large">
		{% trans "Your public profile information has been updated successfully" %}.
	</p>
{% endblock %}

{% block content-related %}
<div class="box">
  <h3>{% trans "Public information" %}</h3>
  <p>{% trans "Select the information you have inserted on your profile that you want to make public" %}.</p>
</div>
{% endblock %}

tags/0.5/userprofile/templates/userprofile/profile/personal.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Edit your personal information" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extracss %}
	<link rel="stylesheet" href="{{ MEDIA_URL }}css/ui.datepicker.css" type="text/css" />
{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/ui.datepicker.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.profile.js"></script>
<script type="text/javascript">
	function updateInline(dateStr) {
		var arrdate = dateStr.split("/");
		$("#id_birthdate").val(arrdate[2] + "-" + arrdate[0] + "-" + arrdate[1]);
	}
	$(function() {
		$("input[type='text']").addClass("text");
		$("#id_firstname").focus();
	});
</script>
{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<form action="{{ request.path }}" method="post" enctype="multipart/form-data">
	<fieldset>
		<legend>{% trans "Edit your personal information" %}</legend>
	
		<label for="id_firstname">{% trans "First Name:" %}</label>
		<p>{{ form.firstname }}</p>
		<label for="id_surname">{% trans "Surname:" %}</label>
		<p>{{ form.surname }}</p>
		<label for="id_gender">{% trans "Gender:" %}</label>
		<p style="overflow: hidden;">
			<a class="male" href="{{ request.path }}">{% trans "Male" %}</a>
			<a class="female" href="{{ request.path }}">{% trans "Female" %}</a>
		</p>
	
		<label for="id_birthdate">{% trans "Birth date:" %}</label>
		<div class="calendar"></div>
		<label for="id_url">{% trans "Url:" %}</label>
		<p>{{ form.url }}</p>
		<label for="id_about">{% trans "About:" %}</label>
		<p>{{ form.about }}</p>
		<div class="hide">{{ form.birthdate }}{{ form.gender }}</div>
	</fieldset>
	<input type="submit" value="{% trans 'Save' %}" />
	</form>
{% endblock %}

{% block content-related %}
  <div class="box">
    <h3>{% trans "Personal information" %}</h3>
    <p>{% trans "Insert some information about you. Once inserted, you can make it public going to the" %} <a href="/accounts/profile/edit/public/">{% trans "public information page" %}</a>.</p>
  </div>
{% endblock %}